apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: soffit-go
  namespace: uportal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: uportal-go
        type: soffit
        tier: backend
    spec:
      containers:
      - name: soffit-go
        image: docker.astuart.co:5000/soffit-go:1466140077
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: conf
          mountPath: /soffit/conf
        env:
        - name: CONF_FILE
          value: /soffit/conf/soffit.yaml
        - name: ENDPOINT
          value: https://soffit-go.test.astuart.co
        - name: SERVICE_NAME
          value: soffit-go.uportal.svc.cluster.local
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        ports:
        - containerPort: 8089
          protocol: TCP
          name: web
        - containerPort: 8443
          protocol: TCP
          name: https
      volumes:
      - name: conf
        secret:
          secretName: soffit-go-conf
---
apiVersion: v1
kind: Service
metadata:
  name: soffit-go
  namespace: uportal
spec:
  ports:
  - port: 80
    targetPort: 8089
    name: http
  - port: 443
    targetPort: 8443
    name: https
  selector:
    app: uportal-go
    type: soffit
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: soffit-go
  namespace: uportal
spec:
  tls:
  - secretName: soffit-go.test.astuart.co.tls
    hosts:
    - soffit-go.test.astuart.co
  rules:
  - host: soffit-go.test.astuart.co
    http:
      paths:
      - path: /
        backend:
          serviceName: soffit-go
          servicePort: 80
